name: Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Hubi gradlew inuu executable yahay
      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: riyobox-android

      # Nadiifi kadibna dhis Debug APK (signing ma rabo)
      - name: Build Debug APK
        run: |
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace
        working-directory: riyobox-android

      # Si toos ah u hel APK-ga
      - name: Find APK
        run: |
          APK_PATH=$(find riyobox-android -type f -name "*debug*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "❌ NO APK FOUND"
            exit 1
          fi
          echo "✅ APK FOUND AT: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV

      # U dir Firebase
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: ${{ env.APK_PATH }}
